### PR TITLE
UX/UI fixes & enhancements

### PR DESCRIPTION
**Pull request by lunaticwhat**
ngl THE UI IS BAD

changes:
- UI colors enhancement
- fixed global padding padding for header text
- centered track list in search
- "More" at home screen should be "Edit" will be more accurate
- and some more i actually forgor

sex: 
l1
l2

### CODE REVIEW

**Comment by Arikatsu** [comment]
Cant test rn, I'm outside. But as for `edit`, Home Page only shows upto 6 entire in each column whereas the entire list is inside that menu. Playlists' edit menu only gives u an option to create Playlists and Downloads doesn't have anything related to edit tbh

**Comment by lunaticwhat** [comment]
ooh so it does only list up to 6 items :skull: I havent try it yet thought clicking on "more" will giving us the same menu but in vertical list. 
okay back to "more"

**Comment by KingRainbow44** [comment]
Please add padding to the bottom of the search page.
image

**Comment by KingRainbow44** [comment]
Please fix the left padding on the playlist list.
image

**Comment by KingRainbow44** [comment]
potential extra padding here not sure
image

**Comment by KingRainbow44** [comment]
Please fix the spacing between the tracks and the side margins.
(should line up with the edit & shuffle buttons)
(additionally, the context menu button shouldn't be overlapping the track title)
image

**Comment by KingRainbow44** [comment]
Please fix the padding between the search bar and the first track displayed.
image

**Review by KingRainbow44 — CHANGES_REQUESTED** [review]
Please fix the changed stated in the comments of this PR. (#1)

**Comment by lunaticwhat** [comment]
wtf i just wake up 💀

**Comment by lunaticwhat** [comment]
tmporaty closed due to conflicts resolving :sob:

**Pull request closed without merging**
